//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceManager._1___Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyFinance
    {
        public System.Guid UUID { get; set; }
        public Nullable<System.Guid> PersonUUID { get; set; }
        public Nullable<System.DateTime> DateMade { get; set; }
        public string Month { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> MonthIncome { get; set; }
        public Nullable<decimal> MonthOutcome { get; set; }
        public Nullable<decimal> NetIncome { get; set; }
        public string Status { get; set; }
    }
}
