//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceManager._1___Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public System.Guid UUID { get; set; }
        public string PersonName { get; set; }
        public Nullable<int> PersonAge { get; set; }
        public Nullable<decimal> PersonMonthlyIncome { get; set; }
        public byte[] PersonImage { get; set; }
        public string Status { get; set; }
    }
}
