//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceManager.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class FMEntities : DbContext
    {
        public FMEntities()
            : base("name=FMEntities")
        {

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<FinanceType> FinanceTypes { get; set; }
        public virtual DbSet<FinanceType_MonthyFinance> FinanceType_MonthyFinance { get; set; }
        public virtual DbSet<MonthlyFinance> MonthlyFinances { get; set; }
        public virtual DbSet<Person> People { get; set; }
    }

}
