//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceManager.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanceType_MonthyFinance
    {
        public System.Guid UUID { get; set; }
        public Nullable<System.Guid> FinanceTypeUUID { get; set; }
        public Nullable<System.Guid> MonthlyFinanceUUID { get; set; }
        public string Status { get; set; }
    }
}
